version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db/postgres
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - log:/app/log
    command: bundle exec rails s -b 0.0.0.0

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest

  log:
    driver: "local"

  monitor:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

volumes:
  db_data:
  bundle_cache:

